# config/meta.yml
meta_product_name: "Keeply"
meta_title: "Keeply - All your stuff, one place"
meta_description: "We help individuals centralize their receipts, track their purchases and warranties, and manage their belongings effortlessly on one seamless platform."
meta_image: "cover.png" # should exist in `app/assets/images/`
